name: Auto Merge to Main

on:
  push:
    branches-ignore:
      - main

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: "Auto-merge ${{ github.ref_name }} into main"
          body: "Automated PR created by workflow to merge ${{ github.ref_name }} into main"
          delete-branch: false

      - name: Auto Merge PR
        if: steps.create_pr.outputs.pull-request-url != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prUrl = '${{ steps.create_pr.outputs.pull-request-url }}';
            const prNumber = prUrl.split('/').pop();
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            await github.pulls.merge({
              owner,
              repo,
              pull_number: prNumber,
              merge_method: 'merge' // or 'squash' or 'rebase'
            });
